import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";

const plex = Nunito({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={plex.className}>{children}</body>
    </html>
  );
}
